# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- checkout: self
  fetchDepth: 0
  
- task: SonarCloudPrepare@4
  inputs:
    SonarQube: 'SonarCloud'
    organization: 'devops-ambara'
    scannerMode: 'dotnet'
    projectKey: 'devops-Ambara_DotNetCoreApi'
    projectName: 'DotNetCoreApi'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build Test Project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: SonarCloudAnalyze@4
  inputs:
     jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@4
  inputs:
     pollingTimeoutSec: '300'

- script: |
    echo "Listing files..."
    ls -R
  displayName: 'Show folder structure'

# - task: SonarQubePrepare@8
#   inputs:
#     SonarQube: 'SonarDocker'
#     scannerMode: 'dotnet'
#     dotnetScannerVersion: '11.2.0.135473'
#     projectKey: 'DotNetCoreApi_DotNetCoreApi_4643e225-bdfa-4cb8-9a70-137d5f5d4519'
#     projectName: 'DotNetCoreApi'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'myWebAPI'
 
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop1

- task: Docker@2
  inputs:
    containerRegistry: 'DotNetCoreApi'
    repository: 'ambarajv/dotnetcoreapi'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/DotNetCoreApi/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/DotNetCoreApi'

# - task: IISWebAppManagementOnMachineGroup@0
#   inputs:
#     EnableIIS: true
#     IISDeploymentType: 'IISWebsite'
#     ActionIISWebsite: 'CreateOrUpdateWebsite'
#     WebsiteName: 'MyDotNetAPI'
#     WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
#     WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'

# - task: IISWebAppDeploymentOnMachineGroup@0
#   inputs:
#     WebSiteName: 'My DotNetAPI'
#     Package: '$(System.DefaultWorkingDirectory)\**\*.zip'