# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: |
    echo "Listing files..."
    ls -R
  displayName: 'Show folder structure'
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'SonarDocker'
    scannerMode: 'dotnet'
    dotnetScannerVersion: '11.2.0.135473'
    projectKey: 'DotNetCoreApi_DotNetCoreApi_4643e225-bdfa-4cb8-9a70-137d5f5d4519'
    projectName: 'DotNetCoreApi'
- task: Docker@2
  inputs:
    containerRegistry: 'DotNetCoreApi'
    repository: 'ambarajv/dotnetcoreapi'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/DotNetCoreApi/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/DotNetCoreApi'